# service/src/doc_agent/prompts/__init__.py
"""
Prompts 模块

包含所有用于文档生成的提示词模板
"""

from .content_processor import (
    V1_DEFAULT_CONTENT_COMPRESSION,
    V1_DEFAULT_KEY_POINTS_EXTRACTION,
    V1_DEFAULT_RESEARCH_DATA_SUMMARY,
    V1_SIMPLE_CONTENT_COMPRESSION,
    V1_SIMPLE_KEY_POINTS_EXTRACTION,
    V1_SIMPLE_RESEARCH_DATA_SUMMARY,
    V2_FAST_CONTENT_COMPRESSION,
    V2_FAST_KEY_POINTS_EXTRACTION,
    V2_FAST_RESEARCH_DATA_SUMMARY,
)
from .outline_generation import (
    V1_DEFAULT as OUTLINE_GENERATION_PROMPT,
    V3_WITH_SUBSECTIONS as OUTLINE_GENERATION_WITH_SUBSECTIONS,
    V4_FAST as OUTLINE_GENERATION_FAST,
)
from .planner import (
    V1_DEFAULT as PLANNER_PROMPT,
    V2_FAST as PLANNER_PROMPT_FAST,
    V3_FAST as PLANNER_PROMPT_FAST_V3,
)
from .supervisor import (
    V1_METADATA_BASED as SUPERVISOR_PROMPT,
    V2_FAST as SUPERVISOR_PROMPT_FAST,
    V3_FAST as SUPERVISOR_PROMPT_FAST_V3,
)
from .writer import (
    V1_DEFAULT as WRITER_PROMPT,
    V1_SIMPLE as WRITER_PROMPT_SIMPLE,
    V3_WITH_SUBSECTIONS as WRITER_PROMPT_WITH_SUBSECTIONS,
    V4_FAST as WRITER_PROMPT_FAST,
)
from .reflection import (
    V1_DEFAULT as REFLECTION_PROMPT,
    V2_FAST as REFLECTION_PROMPT_FAST,
)
from .ai_editor import (
    POLISH_PROFESSIONAL_PROMPT,
    POLISH_FAST_PROMPT,
)

# 为了向后兼容，创建别名
RESEARCH_DATA_SUMMARY_PROMPT = V1_DEFAULT_RESEARCH_DATA_SUMMARY
KEY_POINTS_EXTRACTION_PROMPT = V1_DEFAULT_KEY_POINTS_EXTRACTION
CONTENT_COMPRESSION_PROMPT = V1_DEFAULT_CONTENT_COMPRESSION

__all__ = [
    'OUTLINE_GENERATION_PROMPT', 
    'OUTLINE_GENERATION_WITH_SUBSECTIONS',
    'OUTLINE_GENERATION_FAST',
    'PLANNER_PROMPT', 
    'PLANNER_PROMPT_FAST',
    'PLANNER_PROMPT_FAST_V3',
    'WRITER_PROMPT',
    'WRITER_PROMPT_SIMPLE', 
    'WRITER_PROMPT_WITH_SUBSECTIONS',
    'WRITER_PROMPT_FAST',
    'SUPERVISOR_PROMPT',
    'SUPERVISOR_PROMPT_FAST',
    'SUPERVISOR_PROMPT_FAST_V3',
    'REFLECTION_PROMPT',
    'REFLECTION_PROMPT_FAST',
    'POLISH_PROFESSIONAL_PROMPT',
    'POLISH_FAST_PROMPT',
    'RESEARCH_DATA_SUMMARY_PROMPT', 
    'KEY_POINTS_EXTRACTION_PROMPT',
    'CONTENT_COMPRESSION_PROMPT',
    'V2_FAST_RESEARCH_DATA_SUMMARY',
    'V2_FAST_KEY_POINTS_EXTRACTION',
    'V2_FAST_CONTENT_COMPRESSION',
]
