# AI 辅助文档生成应用配置
# 配置文件说明：
# 1. 模型服务配置：
#    - 企业内网部署的模型
#    - 外部模型
# 2. 检索服务配置：
#    - Elasticsearch 配置
#    - Tavily 网络搜索配置
# 3. Agent 配置：
#    - 任务规划器
#    - 检索器
#    - 执行器
#    - 写作器
#    - 验证器
#    - 知识检索器
#    - 混合检索器
#    - 内容创作器
#    - 内容检查器

# ================================================
# Redis 服务配置
# ================================================
redis:
  # 连接模式: "single" | "cluster"
  mode: "single"
  
  # 单节点配置 (mode: "single"
  single:
    host: "redis-storage.common.svc.cluster.local"
    port: 6379
    db: 0
    password: "xJrhp*4mnHxbBWN2grqq"
  
  # 集群配置 (mode: "single"
  cluster:
    nodes:
      - "10.215.149.74:6380"
      - "10.215.149.75:6380"
      - "10.215.149.76:6380"
      - "10.215.149.77:6380"
      - "10.215.149.78:6380"
      - "10.215.149.79:6380"
    max_redirects: 3
    password: "xJrhp*4mnHxbBWN2grqq"
    timeout: 35000
    
    # 连接池配置
    pool:
      max_active: 20
      max_idle: 10
      min_idle: 2
      max_wait: 5000
    
    # 集群刷新配置
    refresh:
      adaptive: true
      period: 30000
    
    # 关闭超时
    shutdown_timeout: 10000
    
    # 重试配置
    retry:
      attempts: 3
      interval: 5000
    
    # 并发配置
    concurrency: 1
supported_models:
  # 企业内网部署的模型
  qwen_2_5_235b_a22b:
    name: "Qwen3-235B-A22B-new (推理)"
    type: "enterprise_generate"
    model_id: "hdy_model"
    # model_id: "Qwen3-235B-A22B"
    # url: ${ONE_API_BASE}
    url: "http://nginx-lb.hdec-copilot.svc.cluster.local:30002/v1"
    # url: "http://10.238.130.30:11242/v1"
    # url: "http://10.238.130.28:10004/v1"
    reasoning: "True"
    description: "千问 235b 最强推理模型量化版"
    # api_key: "${ONE_API_KEY}"
    api_key: "EMPTY"
  reranker:
    name: "reranker"
    type: "enterprise_reranker"
    model_id: "reranker"
    url: "http://nginx-lb.hdec-copilot.svc.cluster.local:11225/reranker"
    description: "reranker - 重排序模型，擅长重排序任务"
    api_key: "EMPTY"
  gte_qwen:
    name: "gte_qwen"
    type: "enterprise_embedding"
    model_id: "gte_qwen"
    url: "http://nginx-lb.hdec-copilot.svc.cluster.local:11243/embed"
    description: "gte_qwen - 嵌入模型"
    api_key: "EMPTY"
 
# ================================================
# 检索服务配置
# ================================================
# Elasticsearch 配置
elasticsearch:
  hosts:
    - "https://10.238.130.43:9200"
    - "https://10.238.130.44:9200" 
    - "https://10.238.130.45:9200"
  port: 9200
  scheme: "https"
  username: "devops"
  password: "mQxMg8wEKnN1WExz"
  verify_certs: false
  index_prefix: "doc_gen"
  timeout: 30
  max_retries: 3
  retry_on_timeout: true


# ================================================
# 文档生成配置
# ================================================
document_generation:
  # ES 检索配置
  es_search:
    # 向量检索召回数量
    vector_recall_size: 20
    # 混合检索召回数量  
    hybrid_recall_size: 15
    # 重排序后保留数量
    rerank_size: 8
    # 最小相关度分数阈值
    min_score: 0.3
  
  # 文档长度配置
  document_length:
    # 总文档目标字数
    total_target_words: 8000
    # 每个章节目标字数（自动计算）
    chapter_target_words: 1600
    # 章节数量（自动计算）
    chapter_count: 5
    # 最小章节字数
    min_chapter_words: 800
    # 最大章节字数
    max_chapter_words: 2500
  
  # 生成复杂度配置
  generation_complexity:
    # 复杂度级别: "fast" | "standard" | "comprehensive"
    level: "fast"
    
    # 快速模式配置
    fast:
      # 搜索配置
      initial_search_queries: 2       # 初始研究查询数
      chapter_search_queries: 2       # 每章节搜索查询数
      max_search_results: 3           # 每个查询最大结果数
      data_truncate_length: 5000      # 数据截断长度
      
      # 章节配置
      max_chapters: 2                 # 最大章节数
      chapter_target_words: 600       # 每章目标字数
      total_target_words: 1200        # 总目标字数
      
      # 检索配置
      vector_recall_size: 10
      hybrid_recall_size: 8
      rerank_size: 5
      
      # 提示词配置
      use_simplified_prompts: true    # 使用简化提示词
      
      # 超时和重试
      llm_timeout: 60                 # LLM调用超时（秒）
      max_retries: 2                  # 最大重试次数
    
    # 标准模式配置
    standard:
      # 搜索配置
      initial_search_queries: 5
      chapter_search_queries: 3
      max_search_results: 5
      data_truncate_length: 10000
      
      # 章节配置
      max_chapters: 5
      chapter_target_words: 1600
      total_target_words: 8000
      
      # 检索配置
      vector_recall_size: 20
      hybrid_recall_size: 15
      rerank_size: 8
      
      # 提示词配置
      use_simplified_prompts: false
      
      # 超时和重试
      llm_timeout: 180
      max_retries: 5
    
    # 全面模式配置
    comprehensive:
      # 搜索配置
      initial_search_queries: 8
      chapter_search_queries: 5
      max_search_results: 10
      data_truncate_length: -1        # 不截断
      
      # 章节配置
      max_chapters: -1                # 不限制
      chapter_target_words: 2000
      total_target_words: 15000
      
      # 检索配置
      vector_recall_size: 30
      hybrid_recall_size: 20
      rerank_size: 12
      
      # 提示词配置
      use_simplified_prompts: false
      
      # 超时和重试
      llm_timeout: 300
      max_retries: 8

# ================================================
# Agent 配置
# ================================================
agent_config:
  # 默认 LLM 设置
  # default_llm: "gemini_2_5_pro"
  default_llm: "qwen_2_5_235b_a22b"
  # default_llm: "qwen_72b"

  # 任务规划器
  task_planner:
    name: "task_planner"
    description: "任务规划器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.7
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180
  
  # 检索器
  retriever:
    name: "retriever"
    description: "检索器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.7
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180
  
  # 执行器
  executor:
    name: "executor"
    description: "执行器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.7
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180
  
  # 写作器
  composer:
    name: "composer"
    description: "写作器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.8  # 稍高的创造性
    max_tokens: 3000  # 更多输出
    timeout: 300  # 5分钟超时，写作任务需要更多时间
    retry_count: 8  # 8次重试，写作任务更重要
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 300
  
  # 验证器
  validator:
    name: "validator"
    description: "验证器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.6  # 稍低的创造性，更注重准确性
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180
  
  # 知识检索器
  knowledge_retriever:
    name: "knowledge_retriever"
    description: "知识检索器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.7
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180
  
  # 混合检索器
  hybrid_retriever:
    name: "hybrid_retriever"
    description: "混合检索器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.7
    max_tokens: 2000
    timeout: 240  # 4分钟超时，混合检索需要更多时间
    retry_count: 6  # 6次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 240
  
  # 内容创作器
  content_composer:
    name: "content_composer"
    description: "内容创作器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.8  # 高创造性
    max_tokens: 4000  # 更多输出
    timeout: 360  # 6分钟超时，创作任务需要更多时间
    retry_count: 10  # 10次重试，创作任务最重要
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 360
  
  # 内容检查器
  content_checker:
    name: "content_checker"
    description: "内容检查器"
    provider: "qwen_2_5_235b_a22b"
    model: "qwen_2_5_235b_a22b"
    temperature: 0.6  # 低创造性，注重准确性
    max_tokens: 2000
    timeout: 180  # 3分钟超时，企业模型
    retry_count: 5  # 5次重试
    enable_logging: true
    extra_params:
      connect_timeout: 60
      read_timeout: 180

# ================================================
# 搜索配置
# ================================================
search_config:
  # 搜索轮数配置
  max_search_rounds: 1  # 简化测试模式：2轮搜索
  # max_search_rounds: 5  # 正常模式：5轮搜索
  
  # 每次搜索的查询数量
  max_queries: 1  # 简化测试模式：每个planner最多生成3个查询
  # max_queries: 5  # 正常模式：每个planner最多生成5个查询
  
  # 每个查询返回的结果数量
  max_results_per_query: 3  # 简化测试模式：每个查询最多3个结果
  # max_results_per_query: 5  # 正常模式：每个查询最多5个结果

# 其他配置
log_dir: "logs"
output_dir: "output"
